"""Init

Revision ID: 2a6b00ead723
Revises: 
Create Date: 2022-11-28 09:33:42.419293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6b00ead723'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainee_email'), 'trainee', ['email'], unique=True)
    op.create_index(op.f('ix_trainee_full_name'), 'trainee', ['full_name'], unique=False)
    op.create_index(op.f('ix_trainee_id'), 'trainee', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainee_id'), table_name='trainee')
    op.drop_index(op.f('ix_trainee_full_name'), table_name='trainee')
    op.drop_index(op.f('ix_trainee_email'), table_name='trainee')
    op.drop_table('trainee')
    # ### end Alembic commands ###
