"""Add trainee_to_course table

Revision ID: 7216ab25333f
Revises: 477d45835123
Create Date: 2022-11-28 12:15:50.157292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7216ab25333f'
down_revision = '477d45835123'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
