"""Fix trainee_to_course table

Revision ID: 89fd1c274b8f
Revises: 7216ab25333f
Create Date: 2022-11-28 12:39:39.590012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89fd1c274b8f'
down_revision = '7216ab25333f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TraineeToCourse',
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('blurb', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainee.id'], ),
    sa.PrimaryKeyConstraint('trainee_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TraineeToCourse')
    # ### end Alembic commands ###
